---
title: "Working with databases in R"
subtitle: "Christopher Maronga"
institute: "NHS-R Community"
output:
  xaringan::moon_reader:
    css: 
      - default
      - css/nhsr.css
      - css/nhsr-fonts.css
    lib_dir: libs
    seal: false
    self_contained: true
    nature:
      highlightStyle: googlecode
      highlightLines: true
      highlightLanguage: ["r"]
      countIncrementalSlides: false
      ratio: "16:9"
    includes:
      after_body: [css/insert-logo.html]
---

```{r libs, include=FALSE}
library(knitr)
library(tidyverse)
library(xaringan)
library(magick)
library(dbplyr)
#remotes::install_github("mitchelloharawild/icons")
library(icons)
library(xaringanExtra)
library(RSQLite)

xaringanExtra::use_share_again() # need to get the slide button on html view

opts_chunk$set(
  echo = FALSE,
  eval = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.width = 7.252,
  fig.height = 4,
  dpi = 300,
  dev.args = list(type = "cairo")
)
```



class: title-slide, left, bottom

# `r rmarkdown::metadata$title`
----
## **`r rmarkdown::metadata$subtitle`**
### `r rmarkdown::metadata$author`
### `r rmarkdown::metadata$date`

---
  
About me:

- Talk about my education and professional experience


---
Objectives/scope and mode of delivery

- Efficiently connect R to a RDBMS
- Querying data stored within the RDBMS from within R
- REDCap and API
- API security
- Automation via cron jobs

---
Background of RDBMS:

- Brief overview and popular RDBMS


---
Background of REDCap:

- Web-based and used within most health research

---
Ways to connect to RDBMS

- applicable odbc
- DBI compliant package
- Using SQL code chunk (rmarkdown) with either options 1 or 2


---
Ways to Query the data:

- Using DBI function
- dplyr syntax (no need for SQL knowledge, just tidyverse)
  - Advantages:
     - Efficiency (computation is pushed to the database)
     - Memory efficient: collect into R only required dataset
     - All your code is in R, SQL not necessarily needed
  
- Run SQL code chunks in rmarkdwon files










